site_name: Organiq&trade;
site_description: Interact with Tessel from the web.
repo_url: https://github.com/organiq/nodejs
copyright: Copyright &copy; 2014 Myk Willis & Company, LLC. All Rights Reserved. Organiq is a trademark of Myk Willis & Company, LLC.

pages:
- [index.md, Home]
- [hello.md, "Getting Started"]
- [devices.md, "Guide", "Implementing Devices"]
- [registration.md, "Guide", "Device Registration and Discovery"]
- [promises.md, "Guide", "Asynchronous operations with Promises"]
- [cli.md, "Guide", "Using the CLI"]
- [faq.md, "FAQ"]
